apiVersion: v1
entries:
  guacamole:
  - apiVersion: v2
    appVersion: 1.6.0
    created: "2026-02-07T16:02:44.521037612+01:00"
    description: A Helm chart for deploying Guacamole, a clientless remote desktop
      gateway that supports standard protocols like VNC, RDP, and SSH.
    digest: 4760428978c548d109362066d13d2e8814f784fb71ca80bf89c7597fd4b7e059
    home: https://guacamole.apache.org/
    icon: https://guacamole.apache.org/images/logos/guac-tricolor-logo.svg
    name: guacamole
    sources:
    - https://github.com/apache/guacamole-client
    - https://github.com/apache/guacamole-server
    type: application
    urls:
    - https://Edo78.github.io/charts/guacamole-0.3.2.tgz
    version: 0.3.2
generated: "2026-02-07T16:02:44.517347639+01:00"
